### ISSUE TITLE
Add tag for 3.4.6_1.5.5

### ISSUE THREAD

**Issue by saulshanabrook** [mbabineau/docker-zk-exhibitor#8]
It [looks liked](https://registry.hub.docker.com/u/mbabineau/zookeeper-exhibitor/tags/manage/) there is no docker tag for version `3.4.6_1.5.5`. Do you think you could add one so I could pin the image to that version?

**Comment by mbabineau** [comment]
Thought I had already done this, but turns out I was pointing at a (non-existent) branch instead of a tag.

[Fixed](https://registry.hub.docker.com/u/mbabineau/zookeeper-exhibitor/tags/manage/)!

**Comment by saulshanabrook** [comment]
@mbabineau Thank you!
