### ISSUE TITLE
IAM Support

### ISSUE THREAD

**Issue by cfortier2** [mbabineau/docker-zk-exhibitor#9]
Hello,

I'm attempting to get this running using an IAM role as opposed to passing in access/secret keys. Is this supported? If so, what are the steps?

Thanks!

Chris

**Comment by cfortier2** [comment]
Specifically, I'm seeing this issue:

```
INFO  com.netflix.exhibitor.core.activity.ActivityLog  ZooKeeper Server: Starting zookeeper ... STARTED [pool-3-thread-1]
ERROR com.netflix.exhibitor.core.activity.ActivityLog  Unhandled exception in repeating activity (AutomaticInstanceManagement) - re-queueing [ActivityQueue-0]
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 45F4992716A7D375), S3 Extended Request
```

**Comment by guizmaii** [comment]
Maybe, look first at Exhibitor if it supports what you need as it's Exhibitor that needs S3 credentials.

The documentation of Exhibitor : https://github.com/Netflix/exhibitor/wiki

**Comment by cfortier2** [comment]
Exhibitor supports it as long as the `--s3credentials` argument is not passed in. But this containerized version doesn't seem to handle it correctly, so i'm trying to dig in to the root cause.

https://groups.google.com/forum/#!msg/exhibitor-users/l0SZ9Nz-nto/c3aBGr8rAfQJ

**Comment by brandongalbraith** [comment]
@cfortier2 The logic in the wrapper.sh file [1] would need to be modified to support the IAM use case (if `--s3credentials` not provided, use IAM creds). 

[1] https://github.com/mbabineau/docker-zk-exhibitor/blob/master/include/wrapper.sh

**Comment by cfortier2** [comment]
which login are you seeing? 

The script would _seem_ to handle it by not passing the `AWS_ACCESS_KEY_ID`environment variable. I'm able to `docker exec` in to the running container and access the s3 bucket as expected.
